language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy cython
- source activate test-environment
- pip install -r requirements.txt
- python setup.py develop
script:
- py.test --cov=falafel tests/ -m webtest
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: msyriac
  password:
    secure: e4wj1DULCNsNKIOei4ouXKqIXAacOMzgbNkhxU7LetEAh/a4j7DciENPHgp97A/+m6srJEUHhKNubJX/SsDkOB23a+H9M+ksDrCwqLewyeTev2p+mSwEMZg8Cwuu1EXfbCjoSgOjdWVmkDukBUxOnKJGRMStAn1l3rS54BWUUQzW8PDlQSlw9b6OwNZZea3pUV+C88pIZOPtjfImgchdJbYHhnexnENzCThN6reSPYPCRW+d0wf1DIR5GwreTBCxVMCOEd9h1WC4tOqDncMXATRfENufngqQyQFY+fIU+Bqt2/vh1o2XevsUDl3ADtBJJdT1PkEgzq9ABaPnODPRkg0dznSYrvLZdRG0qg5UbBw+xabHdJAda+pUrakv7dHBpjALOgb8TrUl5nMCJHH7/2Z/xV1N72CRTaPKJswdB0F8d7OE1kMrQxHkOwaVUadT6vPhzIF4vD/G0IFmqoxLW6EVsff6r59H4GvkPUAX4IEFuuQfsSwWedUe72dAQZWyevlMhf1ubgaZnk2ScUnl0J0NT8mg+9dCJyqloaEJDf20w1u5Fq0eG0oQCernsKHavk4wQVaoWGC6ad6tNGy++5q/wVvYO9XBFi2wecIv0RoUSjfQ0Dmc0ziW0p/kZG/s0O0VVfbWOdTAE2Erat1ChXTWZLe+7mMUX0Yob1e2tpE=
  on:
    tags: true
    repo: simonsobs/falafel
    python: 3.6
addons:
  apt_packages:
  - gfortran
